import { ProductDeal } from './types';

export const POPULAR_KEYWORDS = [
  'พัดลม',
  'หูฟังบลูทูธ',
  'อาหารแมว Kaniva',
  'พาวเวอร์แบงค์ Eloop',
  'หม้อทอดไร้น้ำมัน',
  'ครีมกันแดด MizuMi',
  'พัดลมพกพา Jisulife',
  'กล้องวงจรปิด Tapo',
  'น้ำยาซักผ้า Breeze',
];

export const MOCK_DEALS: ProductDeal[] = [
  {
    id: 'deal-1',
    title: 'Baseus Bowie H1 Pro หูฟังไร้สายครอบหู ระบบตัดเสียงรบกวน ANC 48dB แบตเตอรี่อึด 70 ชม.',
    imageUrl: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    category: 'หูฟังบลูทูธ',
    tags: ['หูฟัง', 'บลูทูธ', 'ANC', 'Baseus'],
    platform: 'tiktok',
    storeName: 'Baseus Thailand Official Shop',
    storeType: 'mall',
    storeRating: 4.9,
    soldCount: 18450,
    basePrice: 1090,
    originalPrice: 1890,
    marketAvgPrice: 1350,
    estimatedFinalPrice: 940,
    vipFinalPrice: 870,
    activeViewersCount: 28,
    priceAdvice: 'buy_now',
    priceAdviceNote: 'ราคา ฿940 บน TikTok Shop ถูกสุดในรอบ 30 วัน แนะนำซื้อเลย (ต่ำกว่าค่าเฉลี่ยตลาด ฿410)',
    priceHistory: [
      { date: '30 วันก่อน', price: 1390 },
      { date: '21 วันก่อน', price: 1250 },
      { date: '14 วันก่อน', price: 1190 },
      { date: '7 วันก่อน', price: 1090 },
      { date: 'เมื่อวาน', price: 990 },
      { date: 'วันนี้', price: 940 },
    ],
    reviewHighlights: [
      { tag: 'ตัดเสียงรบกวน ANC เงียบกริบ', type: 'pro', percentage: 98 },
      { tag: 'แบตเตอรี่อึด 70 ชม. จริง', type: 'pro', percentage: 96 },
      { tag: 'ฟองน้ำนุ่มไม่บีบหู', type: 'pro', percentage: 94 },
      { tag: 'เบสหนักสะใจ', type: 'pro', percentage: 91 },
      { tag: 'กล่องหูฟังค่อนข้างใหญ่ พกพาต้องใช้พื้นที่', type: 'con', percentage: 12 },
    ],
    voucherStackFormula: {
      basePrice: 1090,
      platformDiscount: 150,
      storeDiscount: 50,
      shippingDiscount: 45,
      finalPrice: 940,
    },
    hasOptionBait: true,
    baitWarningNote: 'ตรวจพบตัวเลือก 59.- ในบางร้าน (เป็นเพียงสาย AUX 3.5mm) ตัวเครื่องจริงเริ่มที่ 1,090.-',
    thaiAuthenticityScore: 97,
    authenticitySummary: 'รีวิวคนไทยแท้ 97% มีภาพเปิดกล่องใช้งานจริง ไม่พบแพทเทิร์นแปลบอทจีน',
    reviews: [
      {
        id: 'r1',
        author: 'น้องแพรว_รีวิวของแท้',
        comment: 'ตัดเสียงดีมากกกกก ใส่อ่านหนังสือคือเงียบกริบ แบตอึดจริงชาร์จทีเดียวใช้อยู่เป็นอาทิตย์ คุ้มสุดๆ 555+',
        isAuthenticThai: true,
        authenticityNote: 'ภาษาพูดธรรมชาติ มีการลากเสียงและบริบทการใช้งานจริง',
        rating: 5,
        date: '2 วันที่แล้ว',
      },
      {
        id: 'r2',
        author: 'Kitti_K',
        comment: 'จัดส่งไวมาก แพ็คบับเบิ้ลมาหนาแน่น เสียงเบสแน่นตามสไตล์ Baseus ของแท้มีสติ๊กเกอร์รับประกัน 1 ปี',
        isAuthenticThai: true,
        authenticityNote: 'ตรวจสอบใบรับประกันและระบุรายละเอียดการแพ็คชัดเจน',
        rating: 5,
        date: '5 วันที่แล้ว',
      }
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v1',
        code: 'TTMALL150',
        discountText: 'ลด 150.- เมื่อช้อปครบ 1,000.-',
        minSpend: 1000,
        discountAmount: 150,
        tag: 'แพลตฟอร์ม'
      },
      {
        id: 'v2',
        code: 'BASEUS50',
        discountText: 'คูปองร้านค้าลดเพิ่ม 50.-',
        minSpend: 800,
        discountAmount: 50,
        tag: 'ร้านค้า'
      }
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'tiktok',
        price: 1090,
        estimatedAfterVoucher: 940,
        storeName: 'Baseus Official (TikTok Shop)',
        storeType: 'mall',
        url: 'https://www.tiktok.com/@baseus.thailand',
        inStock: true,
      },
      {
        platform: 'shopee',
        price: 1190,
        estimatedAfterVoucher: 1020,
        storeName: 'Baseus Official Store (Shopee Mall)',
        storeType: 'mall',
        url: 'https://shopee.co.th/baseus_official',
        inStock: true,
      },
      {
        platform: 'lazada',
        price: 1250,
        estimatedAfterVoucher: 1080,
        storeName: 'Baseus Flagship Store (LazMall)',
        storeType: 'mall',
        url: 'https://www.lazada.co.th/shop/baseus',
        inStock: true,
      }
    ],
    stores: [
      {
        id: 's1-1',
        platform: 'tiktok',
        storeName: 'Baseus Thailand Official (TikTok Shop)',
        storeType: 'mall',
        price: 1090,
        estimatedAfterVoucher: 940,
        voucherNote: 'โค้ดไลฟ์ลด 150.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 8200,
        isLowestOverall: true,
        url: 'https://www.tiktok.com/@baseus.thailand'
      },
      {
        id: 's1-2',
        platform: 'shopee',
        storeName: 'Baseus Official Store (Shopee Mall)',
        storeType: 'mall',
        price: 1190,
        estimatedAfterVoucher: 1020,
        voucherNote: 'โค้ด Shopee Mall ลด 10%',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 6500,
        url: 'https://shopee.co.th/baseus_official'
      },
      {
        id: 's1-3',
        platform: 'shopee',
        storeName: 'Gadget Mania BKK (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 1220,
        estimatedAfterVoucher: 1070,
        voucherNote: 'โค้ดร้านค้าลด 50.-',
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 2300,
        url: 'https://shopee.co.th/gadgetmaniabkk'
      },
      {
        id: 's1-4',
        platform: 'lazada',
        storeName: 'Baseus Flagship Store (LazMall)',
        storeType: 'mall',
        price: 1250,
        estimatedAfterVoucher: 1080,
        voucherNote: 'คูปอง LazMall ลด 80.-',
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 1450,
        url: 'https://www.lazada.co.th/shop/baseus'
      },
      {
        id: 's1-5',
        platform: 'shopee',
        storeName: 'Audio Studio Thailand (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 1280,
        estimatedAfterVoucher: 1130,
        freeShipping: true,
        storeRating: 4.7,
        soldCount: 980,
        url: 'https://shopee.co.th/audiostudio'
      }
    ],
    affiliateUrl: 'https://shope.ee/truedeal-redirect-baseus'
  },
  {
    id: 'deal-2',
    title: 'อาหารแมว Kaniva เม็ดเล็ก กลิ่นหอม บำรุงขนและผิวหนัง สูตรเนื้อแซลมอน ทูน่า และข้าว (กระสอบ 10kg)',
    imageUrl: 'https://images.unsplash.com/photo-1589924691995-400dc9ecc119?w=600&auto=format&fit=crop&q=80',
    category: 'อาหารแมว Kaniva',
    tags: ['อาหารแมว', 'Kaniva', 'คานิว่า', 'แมว', 'อาหารสัตว์'],
    platform: 'shopee',
    storeName: 'Kaniva Official Shop',
    storeType: 'mall',
    storeRating: 4.9,
    soldCount: 42100,
    basePrice: 1269,
    originalPrice: 1450,
    marketAvgPrice: 1390,
    estimatedFinalPrice: 1119,
    vipFinalPrice: 1040,
    hasOptionBait: true,
    baitWarningNote: 'บางร้านมีตัวเลือก 1kg ในราคา 149.- ตรวจสอบแล้วกระสอบ 10kg ราคาที่ดีสุดคือ 1,269.-',
    thaiAuthenticityScore: 99,
    authenticitySummary: 'รีวิวคนไทยแท้ 99% รูปรีวิวน้องแมวกินจริงกว่า 3,000 ภาพ',
    reviews: [
      {
        id: 'r3',
        author: 'ทาสแมวเบอร์หนึ่ง',
        comment: 'เจ้านายที่บ้านชอบมาก ขนนุ่มขึ้นจริงไม่ร่วงเต็มโซฟา ร้านส่งไวสั่งรอบที่ 5 แล้วค่ะ ได้โค้ดส่งฟรีด้วยคุ้มมากก',
        isAuthenticThai: true,
        authenticityNote: 'ภาษาคนรักสัตว์ รีวิวผลลัพธ์ระยะยาวจริง',
        rating: 5,
        date: 'เมื่อวานนี้',
      }
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v3',
        code: 'PETDAY150',
        discountText: 'โค้ดสัตว์เลี้ยงลด 150.-',
        minSpend: 1200,
        discountAmount: 150,
        tag: 'แพลตฟอร์ม'
      }
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'shopee',
        price: 1269,
        estimatedAfterVoucher: 1119,
        storeName: 'Kaniva Official (Shopee Mall)',
        storeType: 'mall',
        url: 'https://shopee.co.th/kaniva_petfood',
        inStock: true,
      },
      {
        platform: 'lazada',
        price: 1310,
        estimatedAfterVoucher: 1190,
        storeName: 'Kaniva Pet Official (LazMall)',
        storeType: 'mall',
        url: 'https://www.lazada.co.th/shop/kaniva',
        inStock: true,
      },
      {
        platform: 'tiktok',
        price: 1350,
        estimatedAfterVoucher: 1230,
        storeName: 'Kaniva Live Shop',
        storeType: 'verified',
        url: 'https://www.tiktok.com/@kanivapet',
        inStock: true,
      }
    ],
    stores: [
      {
        id: 's2-1',
        platform: 'shopee',
        storeName: 'Kaniva Official (Shopee Mall)',
        storeType: 'mall',
        price: 1269,
        estimatedAfterVoucher: 1119,
        voucherNote: 'โค้ดสัตว์เลี้ยงลด 150.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 32000,
        isLowestOverall: true,
        url: 'https://shopee.co.th/kaniva_petfood'
      },
      {
        id: 's2-2',
        platform: 'shopee',
        storeName: 'PetLovers Superstore (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 1289,
        estimatedAfterVoucher: 1159,
        voucherNote: 'โค้ดร้านลด 40.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 7100,
        url: 'https://shopee.co.th/petlovers'
      },
      {
        id: 's2-3',
        platform: 'lazada',
        storeName: 'Kaniva Pet Official (LazMall)',
        storeType: 'mall',
        price: 1310,
        estimatedAfterVoucher: 1190,
        voucherNote: 'คูปอง LazMall ลด 60.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 3800,
        url: 'https://www.lazada.co.th/shop/kaniva'
      },
      {
        id: 's2-4',
        platform: 'shopee',
        storeName: 'Meow Meow Mart (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 1320,
        estimatedAfterVoucher: 1210,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 1900,
        url: 'https://shopee.co.th/meowmeowmart'
      },
      {
        id: 's2-5',
        platform: 'tiktok',
        storeName: 'Kaniva Live Shop (TikTok)',
        storeType: 'verified',
        price: 1350,
        estimatedAfterVoucher: 1230,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 2200,
        url: 'https://www.tiktok.com/@kanivapet'
      }
    ],
    affiliateUrl: 'https://shope.ee/truedeal-redirect-kaniva'
  },
  {
    id: 'deal-3',
    title: 'Eloop E29 แบตสำรองพาวเวอร์แบงค์ 30,000mAh ชาร์จเร็ว Quick Charge 3.0 / PD 20W แท้ 100%',
    imageUrl: 'https://images.unsplash.com/photo-1609592424364-7548a33a6813?w=600&auto=format&fit=crop&q=80',
    category: 'พาวเวอร์แบงค์ Eloop',
    tags: ['พาวเวอร์แบงค์', 'Eloop', 'แบตสำรอง', 'QC3.0', 'PD20W'],
    platform: 'lazada',
    storeName: 'Eloop & Orsen Flagship Store',
    storeType: 'mall',
    storeRating: 4.8,
    soldCount: 89000,
    basePrice: 659,
    originalPrice: 990,
    marketAvgPrice: 799,
    estimatedFinalPrice: 589,
    vipFinalPrice: 539,
    hasOptionBait: false,
    thaiAuthenticityScore: 95,
    authenticitySummary: 'ตรวจสอบรหัสขูด Serial Number เช็คแท้ผ่านเว็บ Eloop ได้จริงทุกกล่อง',
    reviews: [
      {
        id: 'r4',
        author: 'Somchai_IT',
        comment: 'ขูดเช็คโค้ดบนกล่องแล้ว ขึ้นของแท้ 100% ชาร์จ iPhone ไวมาก ชาร์จได้ 4-5 รอบสบายๆ พกขึ้นเครื่องบินได้พอดีเป๊ะ',
        isAuthenticThai: true,
        authenticityNote: 'เช็คซีเรียลจริง และระบุข้อบังคับสายการบินถูกต้อง',
        rating: 5,
        date: '3 วันที่แล้ว',
      }
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v4',
        code: 'LAZGADGET70',
        discountText: 'คูปองไอทีลด 70.-',
        minSpend: 600,
        discountAmount: 70,
        tag: 'แพลตฟอร์ม'
      }
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'lazada',
        price: 659,
        estimatedAfterVoucher: 589,
        storeName: 'Eloop & Orsen (LazMall)',
        storeType: 'mall',
        url: 'https://www.lazada.co.th/shop/eloop',
        inStock: true,
      },
      {
        platform: 'shopee',
        price: 699,
        estimatedAfterVoucher: 629,
        storeName: 'Eloop Official Shop (Shopee Mall)',
        storeType: 'mall',
        url: 'https://shopee.co.th/eloop_thailand',
        inStock: true,
      },
      {
        platform: 'tiktok',
        price: 720,
        estimatedAfterVoucher: 660,
        storeName: 'Orsen Thailand Shop',
        storeType: 'verified',
        url: 'https://www.tiktok.com/@eloopth',
        inStock: true,
      }
    ],
    stores: [
      {
        id: 's3-1',
        platform: 'lazada',
        storeName: 'Eloop & Orsen Flagship (LazMall)',
        storeType: 'mall',
        price: 659,
        estimatedAfterVoucher: 589,
        voucherNote: 'คูปองไอทีลด 70.-',
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 45000,
        isLowestOverall: true,
        url: 'https://www.lazada.co.th/shop/eloop'
      },
      {
        id: 's3-2',
        platform: 'lazada',
        storeName: 'Power Mall BKK (Lazada ร้านแนะนำ)',
        storeType: 'preferred',
        price: 679,
        estimatedAfterVoucher: 619,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 12000,
        url: 'https://www.lazada.co.th/shop/powermall'
      },
      {
        id: 's3-3',
        platform: 'shopee',
        storeName: 'Eloop Official Shop (Shopee Mall)',
        storeType: 'mall',
        price: 699,
        estimatedAfterVoucher: 629,
        voucherNote: 'โค้ดอิเล็กทรอนิกส์ลด 50.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 38000,
        url: 'https://shopee.co.th/eloop_thailand'
      },
      {
        id: 's3-4',
        platform: 'shopee',
        storeName: 'Gadget King TH (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 710,
        estimatedAfterVoucher: 650,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 8400,
        url: 'https://shopee.co.th/gadgetking'
      },
      {
        id: 's3-5',
        platform: 'tiktok',
        storeName: 'Orsen Thailand Shop (TikTok)',
        storeType: 'verified',
        price: 720,
        estimatedAfterVoucher: 660,
        freeShipping: true,
        storeRating: 4.7,
        soldCount: 5200,
        url: 'https://www.tiktok.com/@eloopth'
      }
    ],
    affiliateUrl: 'https://c.lazada.co.th/t/c.truedeal-eloop'
  },
  {
    id: 'deal-4',
    title: 'Gaabor หม้อทอดไร้น้ำมัน ดิจิตอล ความจุใหญ่ 4.5 ลิตร ปรุงอาหารคลีน ลดไขมัน 90% เมนูภาษาไทย',
    imageUrl: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?w=600&auto=format&fit=crop&q=80',
    category: 'หม้อทอดไร้น้ำมัน',
    tags: ['หม้อทอด', 'หม้อทอดไร้น้ำมัน', 'Gaabor', 'เครื่องใช้ไฟฟ้า'],
    platform: 'tiktok',
    storeName: 'Gaabor Official Store',
    storeType: 'mall',
    storeRating: 4.8,
    soldCount: 31000,
    basePrice: 699,
    originalPrice: 1590,
    marketAvgPrice: 890,
    estimatedFinalPrice: 599,
    vipFinalPrice: 549,
    hasOptionBait: true,
    baitWarningNote: 'บางร้านมีตัวเลือกแผ่นกระดาษรองหม้อ 29.- ต้องเลือกตัวเลือกหม้อทอดไฟฟ้า 4.5L',
    thaiAuthenticityScore: 93,
    authenticitySummary: 'รีวิวภาพการทำอาหารไทย (หมูกรอบ ไก่ย่าง) ภาษาพูดคนไทยแท้',
    reviews: [
      {
        id: 'r5',
        author: 'ครัวคุณแม่บ้านมือใหม่',
        comment: 'ทำหมูกรอบออกมาหนังฟูสะใจมาก ใช้ง่าย เมนูภาษาไทยล้างง่าย กระทะเคลือบไม่ติดเลย ประทับใจมากค่ะ',
        isAuthenticThai: true,
        authenticityNote: 'รีวิวเมนูอาหารและฟังก์ชันการใช้งานภาษาไทยจริง',
        rating: 5,
        date: 'สัปดาห์ที่แล้ว',
      }
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v5',
        code: 'LIVECOOK100',
        discountText: 'คูปองไลฟ์ลด 100.-',
        minSpend: 650,
        discountAmount: 100,
        tag: 'แพลตฟอร์ม'
      }
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'tiktok',
        price: 699,
        estimatedAfterVoucher: 599,
        storeName: 'Gaabor Official Shop (TikTok)',
        storeType: 'mall',
        url: 'https://www.tiktok.com/@gaabor_official',
        inStock: true,
      },
      {
        platform: 'shopee',
        price: 759,
        estimatedAfterVoucher: 679,
        storeName: 'Gaabor Official (Shopee Mall)',
        storeType: 'mall',
        url: 'https://shopee.co.th/gaabor_thailand',
        inStock: true,
      },
      {
        platform: 'lazada',
        price: 790,
        estimatedAfterVoucher: 710,
        storeName: 'Gaabor Flagship (LazMall)',
        storeType: 'mall',
        url: 'https://www.lazada.co.th/shop/gaabor',
        inStock: true,
      }
    ],
    stores: [
      {
        id: 's4-1',
        platform: 'tiktok',
        storeName: 'Gaabor Official Shop (TikTok)',
        storeType: 'mall',
        price: 699,
        estimatedAfterVoucher: 599,
        voucherNote: 'คูปองไลฟ์ลด 100.-',
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 16000,
        isLowestOverall: true,
        url: 'https://www.tiktok.com/@gaabor_official'
      },
      {
        id: 's4-2',
        platform: 'shopee',
        storeName: 'Gaabor Official (Shopee Mall)',
        storeType: 'mall',
        price: 759,
        estimatedAfterVoucher: 679,
        voucherNote: 'โค้ดร้านลด 80.-',
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 9500,
        url: 'https://shopee.co.th/gaabor_thailand'
      },
      {
        id: 's4-3',
        platform: 'shopee',
        storeName: 'Kitchen Pro Mart (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 779,
        estimatedAfterVoucher: 699,
        freeShipping: true,
        storeRating: 4.7,
        soldCount: 2800,
        url: 'https://shopee.co.th/kitchenpromart'
      },
      {
        id: 's4-4',
        platform: 'lazada',
        storeName: 'Gaabor Flagship (LazMall)',
        storeType: 'mall',
        price: 790,
        estimatedAfterVoucher: 710,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 3100,
        url: 'https://www.lazada.co.th/shop/gaabor'
      }
    ],
    affiliateUrl: 'https://www.tiktok.com/@truedeal-gaabor'
  },
  {
    id: 'deal-5',
    title: 'MizuMi UV Water Serum SPF50+ PA++++ ครีมกันแดดสูตรน้ำ 100% Non-Chemical อ่อนโยน สำหรับผิวแพ้ง่าย (40g)',
    imageUrl: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=600&auto=format&fit=crop&q=80',
    category: 'ครีมกันแดด MizuMi',
    tags: ['ครีมกันแดด', 'MizuMi', 'ผิวแพ้ง่าย', 'สกินแคร์', 'ความงาม'],
    platform: 'shopee',
    storeName: 'MizuMi Official Store',
    storeType: 'mall',
    storeRating: 4.9,
    soldCount: 95000,
    basePrice: 445,
    originalPrice: 890,
    marketAvgPrice: 590,
    estimatedFinalPrice: 385,
    vipFinalPrice: 345,
    hasOptionBait: true,
    baitWarningNote: 'บางร้านมีตัวเลือกขนาดพกพา 8g ในราคา 89.- อันนี้คือไซส์จริง 40g ซื้อโปร 1 แถม 1 หรือลดพิเศษ',
    thaiAuthenticityScore: 98,
    authenticitySummary: 'สินค้าความงามยอดฮิต รีวิวสภาพผิวคนไทยจริง ไม่ใช่บอทแปล',
    reviews: [
      {
        id: 'r6',
        author: 'May_BeautyDiary',
        comment: 'กันแดดลูกรัก ใช้มาเกิน 10 ขวดแล้ว ไม่วอก ไม่เป็นคราบ ทา 2 ข้อนิ้วสบายหน้ามาก หน้าไม่เยิ้มระหว่างวัน',
        isAuthenticThai: true,
        authenticityNote: 'ศัพท์บิวตี้ไทยธรรมชาติ (ทา 2 ข้อนิ้ว, หน้าไม่เยิ้ม)',
        rating: 5,
        date: '4 วันที่แล้ว',
      }
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v6',
        code: 'BEAUTY60',
        discountText: 'คูปองบิวตี้ลด 60.-',
        minSpend: 400,
        discountAmount: 60,
        tag: 'แพลตฟอร์ม'
      }
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'shopee',
        price: 445,
        estimatedAfterVoucher: 385,
        storeName: 'MizuMi Official (Shopee Mall)',
        storeType: 'mall',
        url: 'https://shopee.co.th/mizumi_official',
        inStock: true,
      },
      {
        platform: 'lazada',
        price: 489,
        estimatedAfterVoucher: 429,
        storeName: 'MizuMi Official (LazMall)',
        storeType: 'mall',
        url: 'https://www.lazada.co.th/shop/mizumi',
        inStock: true,
      },
      {
        platform: 'tiktok',
        price: 499,
        estimatedAfterVoucher: 449,
        storeName: 'MizuMi Thailand',
        storeType: 'mall',
        url: 'https://www.tiktok.com/@mizumi_th',
        inStock: true,
      }
    ],
    stores: [
      {
        id: 's5-1',
        platform: 'shopee',
        storeName: 'MizuMi Official (Shopee Mall)',
        storeType: 'mall',
        price: 445,
        estimatedAfterVoucher: 385,
        voucherNote: 'คูปองบิวตี้ลด 60.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 65000,
        isLowestOverall: true,
        url: 'https://shopee.co.th/mizumi_official'
      },
      {
        id: 's5-2',
        platform: 'shopee',
        storeName: 'CosmeBox Thailand (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 469,
        estimatedAfterVoucher: 419,
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 14000,
        url: 'https://shopee.co.th/cosmebox'
      },
      {
        id: 's5-3',
        platform: 'lazada',
        storeName: 'MizuMi Official (LazMall)',
        storeType: 'mall',
        price: 489,
        estimatedAfterVoucher: 429,
        voucherNote: 'คูปองบิวตี้ลด 40.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 12000,
        url: 'https://www.lazada.co.th/shop/mizumi'
      },
      {
        id: 's5-4',
        platform: 'tiktok',
        storeName: 'MizuMi Thailand (TikTok Shop)',
        storeType: 'mall',
        price: 499,
        estimatedAfterVoucher: 449,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 8900,
        url: 'https://www.tiktok.com/@mizumi_th'
      }
    ],
    affiliateUrl: 'https://shope.ee/truedeal-mizumi'
  },
  {
    id: 'deal-6',
    title: 'Jisulife Life9 พัดลมพกพามือถือ ลมแรงสะใจ ปรับได้ 5 ระดับ แบตเตอรี่อึด 5000mAh น้ำหนักเบา',
    imageUrl: 'https://images.unsplash.com/photo-1618941716939-553df3c6c278?w=600&auto=format&fit=crop&q=80',
    category: 'พัดลมพกพา Jisulife',
    tags: ['พัดลม', 'พัดลมพกพา', 'Jisulife', 'คลายร้อน', 'พัดลมมือถือ'],
    platform: 'shopee',
    storeName: 'Jisulife Official Thailand',
    storeType: 'mall',
    storeRating: 4.9,
    soldCount: 54000,
    basePrice: 539,
    originalPrice: 890,
    marketAvgPrice: 650,
    estimatedFinalPrice: 479,
    vipFinalPrice: 439,
    activeViewersCount: 42,
    priceAdvice: 'buy_now',
    priceAdviceNote: 'ราคา ฿479 บน Shopee Mall ถูกสุดในรอบ 30 วัน แนะนำซื้อเลย',
    priceHistory: [
      { date: '30 วันก่อน', price: 650 },
      { date: '21 วันก่อน', price: 590 },
      { date: '14 วันก่อน', price: 539 },
      { date: '7 วันก่อน', price: 519 },
      { date: 'เมื่อวาน', price: 499 },
      { date: 'วันนี้', price: 479 },
    ],
    reviewHighlights: [
      { tag: 'ลมแรงมาก พกพาสู้แดดเมืองไทยรอด', type: 'pro', percentage: 98 },
      { tag: 'แบต 5000mAh ใช้ได้ทั้งวันไม่ต้องชาร์จซ้ำ', type: 'pro', percentage: 96 },
      { tag: 'น้ำหนักเบา ดีไซน์สวยโมเดิร์น', type: 'pro', percentage: 94 },
      { tag: 'เบอร์ 5 มีเสียงมอเตอร์แรงขึ้นเล็กน้อย', type: 'con', percentage: 15 },
    ],
    voucherStackFormula: {
      basePrice: 539,
      platformDiscount: 60,
      storeDiscount: 30,
      shippingDiscount: 35,
      finalPrice: 479,
    },
    hasOptionBait: false,
    thaiAuthenticityScore: 96,
    authenticitySummary: 'รีวิวท้าแดดเมืองไทย ทดสอบความแรงลมและเสียงมอเตอร์แบบละเอียด',
    reviews: [
      {
        id: 'r7',
        author: 'Arm_Traveller',
        comment: 'ลมแรงแบบตกใจ เสียงเบอร์ 5 มีดังบ้างแต่รับได้ ออกแดดจตุจักรคือรอดชีวิตเพราะตัวนี้เลยครับ 555+',
        isAuthenticThai: true,
        authenticityNote: 'ระบุสถานที่แดดจัดในไทย (จตุจักร) ธรรมชาติมาก',
        rating: 5,
        date: 'เมื่อวานนี้',
      }
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v7',
        code: 'SUMMER60',
        discountText: 'ลดทันที 60.-',
        minSpend: 500,
        discountAmount: 60,
        tag: 'แพลตฟอร์ม'
      }
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'shopee',
        price: 539,
        estimatedAfterVoucher: 479,
        storeName: 'Jisulife Official (Shopee Mall)',
        storeType: 'mall',
        url: 'https://shopee.co.th/jisulife_th',
        inStock: true,
      },
      {
        platform: 'tiktok',
        price: 569,
        estimatedAfterVoucher: 509,
        storeName: 'Jisulife Thailand Shop',
        storeType: 'verified',
        url: 'https://www.tiktok.com/@jisulife_th',
        inStock: true,
      },
      {
        platform: 'lazada',
        price: 599,
        estimatedAfterVoucher: 539,
        storeName: 'Jisulife Flagship (LazMall)',
        storeType: 'mall',
        url: 'https://www.lazada.co.th/shop/jisulife',
        inStock: true,
      }
    ],
    stores: [
      {
        id: 's6-1',
        platform: 'shopee',
        storeName: 'Jisulife Official Thailand (Shopee Mall)',
        storeType: 'mall',
        price: 539,
        estimatedAfterVoucher: 479,
        voucherNote: 'โค้ด Shopee Mall ลด 60.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 36000,
        isLowestOverall: true,
        url: 'https://shopee.co.th/jisulife_th'
      },
      {
        id: 's6-2',
        platform: 'tiktok',
        storeName: 'Jisulife Thailand Shop (TikTok)',
        storeType: 'verified',
        price: 569,
        estimatedAfterVoucher: 509,
        voucherNote: 'โค้ดส่งฟรี + ลด 60.-',
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 9200,
        url: 'https://www.tiktok.com/@jisulife_th'
      },
      {
        id: 's6-3',
        platform: 'shopee',
        storeName: 'GadgetZone Express (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 579,
        estimatedAfterVoucher: 529,
        voucherNote: 'โค้ดร้านลด 50.-',
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 4800,
        url: 'https://shopee.co.th/gadgetzone'
      },
      {
        id: 's6-4',
        platform: 'lazada',
        storeName: 'Jisulife Flagship (LazMall)',
        storeType: 'mall',
        price: 599,
        estimatedAfterVoucher: 539,
        voucherNote: 'คูปอง LazMall ลด 40.-',
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 3900,
        url: 'https://www.lazada.co.th/shop/jisulife'
      },
      {
        id: 's6-5',
        platform: 'lazada',
        storeName: 'Power IT Thailand (Lazada ร้านแนะนำ)',
        storeType: 'preferred',
        price: 619,
        estimatedAfterVoucher: 569,
        freeShipping: true,
        storeRating: 4.7,
        soldCount: 1500,
        url: 'https://www.lazada.co.th/shop/powerit'
      },
      {
        id: 's6-6',
        platform: 'shopee',
        storeName: 'Mega Living BKK (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 635,
        estimatedAfterVoucher: 585,
        freeShipping: false,
        storeRating: 4.7,
        soldCount: 850,
        url: 'https://shopee.co.th/megaliving'
      }
    ],
    affiliateUrl: 'https://shope.ee/truedeal-jisulife'
  },
  {
    id: 'deal-11',
    title: 'Hatari พัดลมตั้งโต๊ะ 16 นิ้ว รุ่น HT-T16M5 มอเตอร์ทรงพลัง ปรับแรงลม 3 ระดับ ระบบตัดไฟเทอร์โมฟิวส์ ประหยัดไฟเบอร์ 5',
    imageUrl: 'https://images.unsplash.com/photo-1544725176-7c40e5a71c5e?w=600&auto=format&fit=crop&q=80',
    category: 'พัดลม',
    tags: ['พัดลม', 'Hatari', 'ฮาตาริ', 'พัดลมตั้งโต๊ะ', '16นิ้ว', 'เครื่องใช้ไฟฟ้า'],
    platform: 'lazada',
    storeName: 'Hatari Official Store (LazMall)',
    storeType: 'mall',
    storeRating: 4.9,
    soldCount: 62000,
    basePrice: 598,
    originalPrice: 850,
    marketAvgPrice: 720,
    estimatedFinalPrice: 528,
    vipFinalPrice: 488,
    activeViewersCount: 34,
    priceAdvice: 'buy_now',
    priceAdviceNote: 'ราคา ฿528 บน Lazada ถูกที่สุดในรอบ 30 วัน ซื้อได้เลย คุ้มค่าที่สุด',
    priceHistory: [
      { date: '30 วันก่อน', price: 680 },
      { date: '21 วันก่อน', price: 650 },
      { date: '14 วันก่อน', price: 619 },
      { date: '7 วันก่อน', price: 598 },
      { date: 'เมื่อวาน', price: 568 },
      { date: 'วันนี้', price: 528 },
    ],
    reviewHighlights: [
      { tag: 'มอเตอร์ทองแดงแท้ ลมแรงทนทาน', type: 'pro', percentage: 99 },
      { tag: 'มีระบบเทอร์โมฟิวส์ตัดไฟปลอดภัย', type: 'pro', percentage: 97 },
      { tag: 'ประหยัดไฟเบอร์ 5 จริง', type: 'pro', percentage: 95 },
      { tag: 'แพ็คโฟมแน่นหนากล่องสมบูรณ์', type: 'pro', percentage: 96 },
      { tag: 'สายไฟ 1.2 ม. อาจต้องใช้ปลั๊กพ่วงถ้าปลั๊กไกล', type: 'con', percentage: 14 },
    ],
    voucherStackFormula: {
      basePrice: 598,
      platformDiscount: 70,
      storeDiscount: 30,
      shippingDiscount: 40,
      finalPrice: 528,
    },
    hasOptionBait: false,
    thaiAuthenticityScore: 99,
    authenticitySummary: 'แบรนด์พัดลมเบอร์หนึ่งของคนไทย รีวิวทนทานใช้งานได้ 5-10 ปี สภาพกล่องสมบูรณ์',
    reviews: [
      {
        id: 'r12',
        author: 'วิศวกรสายประหยัด',
        comment: 'พัดลมสามัญประจำบ้านคนไทย มอเตอร์ทองแดงแท้ ลมแรงเงียบ ประหยัดไฟเบอร์ 5 จริง ซื้อร้านทางการมีรับประกันมอเตอร์ 3 ปีเต็ม',
        isAuthenticThai: true,
        authenticityNote: 'ภาษาไทยรีวิวคุณสมบัติทางวิศวกรรมและการรับประกันแท้',
        rating: 5,
        date: '3 วันที่แล้ว',
      }
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v12',
        code: 'HATARI70',
        discountText: 'โค้ดส่วนลดฮาตาริลด 70.-',
        minSpend: 550,
        discountAmount: 70,
        tag: 'ร้านค้า'
      }
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'lazada',
        price: 598,
        estimatedAfterVoucher: 528,
        storeName: 'Hatari Official (LazMall)',
        storeType: 'mall',
        url: 'https://www.lazada.co.th/shop/hatari',
        inStock: true,
      },
      {
        platform: 'shopee',
        price: 619,
        estimatedAfterVoucher: 549,
        storeName: 'Hatari Official (Shopee Mall)',
        storeType: 'mall',
        url: 'https://shopee.co.th/hatari_official',
        inStock: true,
      },
      {
        platform: 'tiktok',
        price: 649,
        estimatedAfterVoucher: 589,
        storeName: 'Hatari Live Thailand',
        storeType: 'verified',
        url: 'https://www.tiktok.com/@hatarithailand',
        inStock: true,
      }
    ],
    stores: [
      {
        id: 's11-1',
        platform: 'lazada',
        storeName: 'Hatari Official Store (LazMall)',
        storeType: 'mall',
        price: 598,
        estimatedAfterVoucher: 528,
        voucherNote: 'คูปองฮาตาริลด 70.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 31000,
        isLowestOverall: true,
        url: 'https://www.lazada.co.th/shop/hatari'
      },
      {
        id: 's11-2',
        platform: 'shopee',
        storeName: 'Hatari Official Store (Shopee Mall)',
        storeType: 'mall',
        price: 619,
        estimatedAfterVoucher: 549,
        voucherNote: 'โค้ด Shopee Mall ลด 50.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 22000,
        url: 'https://shopee.co.th/hatari_official'
      },
      {
        id: 's11-3',
        platform: 'shopee',
        storeName: 'ไทยแสงเจริญ ไฟฟ้า (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 630,
        estimatedAfterVoucher: 580,
        voucherNote: 'โค้ดร้านลด 30.-',
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 5400,
        url: 'https://shopee.co.th/thaisangcharoen'
      },
      {
        id: 's11-4',
        platform: 'lazada',
        storeName: 'Home Electronics Express (Lazada ร้านแนะนำ)',
        storeType: 'preferred',
        price: 639,
        estimatedAfterVoucher: 589,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 2800,
        url: 'https://www.lazada.co.th/shop/homeelec'
      },
      {
        id: 's11-5',
        platform: 'tiktok',
        storeName: 'Hatari Live Thailand (TikTok)',
        storeType: 'verified',
        price: 649,
        estimatedAfterVoucher: 589,
        freeShipping: true,
        storeRating: 4.7,
        soldCount: 1900,
        url: 'https://www.tiktok.com/@hatarithailand'
      }
    ],
    affiliateUrl: 'https://c.lazada.co.th/t/c.truedeal-hatari'
  },
  {
    id: 'deal-7',
    title: 'TP-Link Tapo C210 กล้องวงจรปิด Wi-Fi คมชัด 2K หมุนได้ 360 องศา โหมดกลางคืน ตรวจจับคนด้วย AI พร้อมเสียงสองทาง',
    imageUrl: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600&auto=format&fit=crop&q=80',
    category: 'กล้องวงจรปิด Tapo',
    tags: ['กล้องวงจรปิด', 'Tapo', 'TPLink', 'C210', 'Wi-Fi'],
    platform: 'lazada',
    storeName: 'TP-Link Official Store',
    storeType: 'mall',
    storeRating: 4.9,
    soldCount: 68000,
    basePrice: 779,
    originalPrice: 1290,
    marketAvgPrice: 920,
    estimatedFinalPrice: 699,
    vipFinalPrice: 649,
    hasOptionBait: true,
    baitWarningNote: 'ตัวเลือก 149.- เป็นเพียง Memory Card 32GB ตัวเครื่องกล้องจริงเริ่มที่ 779.-',
    thaiAuthenticityScore: 97,
    authenticitySummary: 'รีวิวติดตั้งใช้งานในบ้านคนไทย ติดตามสัตว์เลี้ยงและคนแก่จริง',
    reviews: [
      {
        id: 'r8',
        author: 'ช่างบอย_สมุทรปราการ',
        comment: 'ภาพคมกริบ 2K ติดไว้ดูแมวที่บ้านตอนไปทำงาน ต่อแอป Tapo ง่ายมาก 2 นาทีเสร็จ สั่งตัวที่ 3 แล้วครับ',
        isAuthenticThai: true,
        authenticityNote: 'ภาษาช่างไทยแท้ มีชื่อรุ่นแอปถูกต้อง',
        rating: 5,
        date: '6 วันที่แล้ว',
      }
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v8',
        code: 'HOMETEK80',
        discountText: 'คูปองอุปกรณ์บ้านลด 80.-',
        minSpend: 750,
        discountAmount: 80,
        tag: 'แพลตฟอร์ม'
      }
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'lazada',
        price: 779,
        estimatedAfterVoucher: 699,
        storeName: 'TP-Link Official (LazMall)',
        storeType: 'mall',
        url: 'https://www.lazada.co.th/shop/tp-link',
        inStock: true,
      },
      {
        platform: 'shopee',
        price: 819,
        estimatedAfterVoucher: 739,
        storeName: 'TP-Link Official Store (Shopee Mall)',
        storeType: 'mall',
        url: 'https://shopee.co.th/tplink_official',
        inStock: true,
      },
      {
        platform: 'tiktok',
        price: 850,
        estimatedAfterVoucher: 780,
        storeName: 'TP-Link Authorized Shop',
        storeType: 'verified',
        url: 'https://www.tiktok.com/@tplinkth',
        inStock: true,
      }
    ],
    stores: [
      {
        id: 's7-1',
        platform: 'lazada',
        storeName: 'TP-Link Official (LazMall)',
        storeType: 'mall',
        price: 779,
        estimatedAfterVoucher: 699,
        voucherNote: 'คูปองลด 80.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 35000,
        isLowestOverall: true,
        url: 'https://www.lazada.co.th/shop/tp-link'
      },
      {
        id: 's7-2',
        platform: 'shopee',
        storeName: 'TP-Link Official Store (Shopee Mall)',
        storeType: 'mall',
        price: 819,
        estimatedAfterVoucher: 739,
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 24000,
        url: 'https://shopee.co.th/tplink_official'
      },
      {
        id: 's7-3',
        platform: 'shopee',
        storeName: 'CCTV Mega Mall (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 835,
        estimatedAfterVoucher: 765,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 6200,
        url: 'https://shopee.co.th/cctvmegamall'
      },
      {
        id: 's7-4',
        platform: 'tiktok',
        storeName: 'TP-Link Authorized Shop',
        storeType: 'verified',
        price: 850,
        estimatedAfterVoucher: 780,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 2800,
        url: 'https://www.tiktok.com/@tplinkth'
      }
    ],
    affiliateUrl: 'https://c.lazada.co.th/t/c.truedeal-tapo'
  },
  {
    id: 'deal-8',
    title: 'บรีส เอกเซล น้ำยาซักผ้าสูตรเข้มข้น พลังเอนไซม์ธรรมชาติ ขจัดคราบหนัก หอมสดชื่นยาวนาน (ยกลัง 12 ถุง)',
    imageUrl: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=600&auto=format&fit=crop&q=80',
    category: 'น้ำยาซักผ้า Breeze',
    tags: ['น้ำยาซักผ้า', 'บรีส', 'Breeze', 'ของใช้ในบ้าน', 'ยกลัง'],
    platform: 'shopee',
    storeName: 'Unilever Home Care Official',
    storeType: 'mall',
    storeRating: 4.9,
    soldCount: 120000,
    basePrice: 629,
    originalPrice: 890,
    marketAvgPrice: 740,
    estimatedFinalPrice: 549,
    vipFinalPrice: 499,
    hasOptionBait: false,
    thaiAuthenticityScore: 99,
    authenticitySummary: 'แม่บ้านคนไทยรีวิวส่งถึงบ้าน ลังแน่นหนา ไม่รั่วซึม',
    reviews: [
      {
        id: 'r9',
        author: 'แม่น้องกัปตัน',
        comment: 'ซื้อยกลังช่วงโปรถูกกว่าโลตัสแถวบ้านเยอะมาก ไม่ต้องแบกเองด้วย ขนส่งส่งถึงหน้าบ้าน ซักสะอาดหอมมากค่ะ',
        isAuthenticThai: true,
        authenticityNote: 'เทียบราคาห้างไทยท้องถิ่นแท้จริง (โลตัส)',
        rating: 5,
        date: '3 วันที่แล้ว',
      }
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v9',
        code: 'UNILEVER80',
        discountText: 'คูปองแบรนด์ยูนิลีเวอร์ลด 80.-',
        minSpend: 600,
        discountAmount: 80,
        tag: 'ร้านค้า'
      }
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'shopee',
        price: 629,
        estimatedAfterVoucher: 549,
        storeName: 'Unilever Official (Shopee Mall)',
        storeType: 'mall',
        url: 'https://shopee.co.th/unilever_homecare',
        inStock: true,
      },
      {
        platform: 'lazada',
        price: 669,
        estimatedAfterVoucher: 599,
        storeName: 'Unilever Flagship (LazMall)',
        storeType: 'mall',
        url: 'https://www.lazada.co.th/shop/unilever',
        inStock: true,
      },
      {
        platform: 'tiktok',
        price: 689,
        estimatedAfterVoucher: 619,
        storeName: 'Unilever TikTok Shop',
        storeType: 'mall',
        url: 'https://www.tiktok.com/@unileverth',
        inStock: true,
      }
    ],
    stores: [
      {
        id: 's8-1',
        platform: 'shopee',
        storeName: 'Unilever Home Care Official (Shopee Mall)',
        storeType: 'mall',
        price: 629,
        estimatedAfterVoucher: 549,
        voucherNote: 'คูปองยูนิลีเวอร์ลด 80.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 78000,
        isLowestOverall: true,
        url: 'https://shopee.co.th/unilever_homecare'
      },
      {
        id: 's8-2',
        platform: 'shopee',
        storeName: 'SuperSave Mart BKK (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 649,
        estimatedAfterVoucher: 589,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 18000,
        url: 'https://shopee.co.th/supersave'
      },
      {
        id: 's8-3',
        platform: 'lazada',
        storeName: 'Unilever Flagship (LazMall)',
        storeType: 'mall',
        price: 669,
        estimatedAfterVoucher: 599,
        voucherNote: 'คูปองลด 50.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 15000,
        url: 'https://www.lazada.co.th/shop/unilever'
      },
      {
        id: 's8-4',
        platform: 'tiktok',
        storeName: 'Unilever TikTok Shop',
        storeType: 'mall',
        price: 689,
        estimatedAfterVoucher: 619,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 9000,
        url: 'https://www.tiktok.com/@unileverth'
      }
    ],
    affiliateUrl: 'https://shope.ee/truedeal-breeze'
  },
  {
    id: 'deal-9',
    title: 'Dreame H12 Dual เครื่องดูดฝุ่นถูพื้นอัจฉริยะ ล้างลูกกลิ้งและเป่าแห้งด้วยลมร้อนอัตโนมัติ 55°C สะอาดไร้กลิ่นอับ',
    imageUrl: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&auto=format&fit=crop&q=80',
    category: 'เครื่องดูดฝุ่น',
    tags: ['เครื่องดูดฝุ่น', 'Dreame', 'ดูดถู', 'ทำความสะอาด', 'เครื่องใช้ไฟฟ้า'],
    platform: 'lazada',
    storeName: 'Dreame Thailand Official',
    storeType: 'mall',
    storeRating: 4.9,
    soldCount: 9400,
    basePrice: 12990,
    originalPrice: 19990,
    marketAvgPrice: 14500,
    estimatedFinalPrice: 11490,
    vipFinalPrice: 10490,
    hasOptionBait: true,
    baitWarningNote: 'ตัวเลือก 390.- คือน้ำยาทำความสะอาดสำรอง ตัวเครื่องชุดเต็มเริ่มที่ 12,990.-',
    thaiAuthenticityScore: 96,
    authenticitySummary: 'รีวิวบ้านคนไทยมีสัตว์เลี้ยง ขนแมวเกลี้ยง พื้นแห้งไว มีวิดีโอทดสอบจริง',
    reviews: [
      {
        id: 'r10',
        author: 'Dr.Korn_BKK',
        comment: 'ชีวิตเปลี่ยนเลยครับ มีหมา 2 ตัวขนร่วงทุกวัน ตัวนี้ดูดพร้อมถูรอบเดียวจบ ระบบเป่าลมร้อนทำให้ลูกกลิ้งไม่มีกลิ่นเหม็นอับเลย คุ้มค่าเงินมาก',
        isAuthenticThai: true,
        authenticityNote: 'ภาษาไทยสุภาพ พร้อมอธิบายฟังก์ชันเป่าแห้งชัดเจน',
        rating: 5,
        date: '2 สัปดาห์ที่แล้ว',
      }
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v10',
        code: 'MEGAHOME1500',
        discountText: 'คูปองเครื่องใช้ไฟฟ้าลด 1,500.-',
        minSpend: 10000,
        discountAmount: 1500,
        tag: 'แพลตฟอร์ม'
      }
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'lazada',
        price: 12990,
        estimatedAfterVoucher: 11490,
        storeName: 'Dreame Official (LazMall)',
        storeType: 'mall',
        url: 'https://www.lazada.co.th/shop/dreame',
        inStock: true,
      },
      {
        platform: 'shopee',
        price: 13490,
        estimatedAfterVoucher: 11990,
        storeName: 'Dreame Thailand Store (Shopee Mall)',
        storeType: 'mall',
        url: 'https://shopee.co.th/dreame_official',
        inStock: true,
      },
      {
        platform: 'tiktok',
        price: 13990,
        estimatedAfterVoucher: 12490,
        storeName: 'Dreame Live Shop',
        storeType: 'mall',
        url: 'https://www.tiktok.com/@dreamethailand',
        inStock: true,
      }
    ],
    stores: [
      {
        id: 's9-1',
        platform: 'lazada',
        storeName: 'Dreame Official Store (LazMall)',
        storeType: 'mall',
        price: 12990,
        estimatedAfterVoucher: 11490,
        voucherNote: 'คูปองลด 1,500.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 5200,
        isLowestOverall: true,
        url: 'https://www.lazada.co.th/shop/dreame'
      },
      {
        id: 's9-2',
        platform: 'shopee',
        storeName: 'Dreame Thailand Store (Shopee Mall)',
        storeType: 'mall',
        price: 13490,
        estimatedAfterVoucher: 11990,
        voucherNote: 'โค้ด Shopee Mall ลด 1,200.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 3100,
        url: 'https://shopee.co.th/dreame_official'
      },
      {
        id: 's9-3',
        platform: 'shopee',
        storeName: 'Smart Living Expert (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 13700,
        estimatedAfterVoucher: 12300,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 820,
        url: 'https://shopee.co.th/smartliving'
      },
      {
        id: 's9-4',
        platform: 'tiktok',
        storeName: 'Dreame Live Shop (TikTok)',
        storeType: 'mall',
        price: 13990,
        estimatedAfterVoucher: 12490,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 1100,
        url: 'https://www.tiktok.com/@dreamethailand'
      }
    ],
    affiliateUrl: 'https://c.lazada.co.th/t/c.truedeal-dreame'
  },
  {
    id: 'deal-10',
    title: 'Hi-Q 1 Plus Super Gold ไฮคิว 1 พลัส ซูเปอร์โกลด์ ซินไบโอโพรเทก สูตร 3 นมผงสำหรับเด็ก 1 ปีขึ้นไป (กล่อง 3000g)',
    imageUrl: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=600&auto=format&fit=crop&q=80',
    category: 'นมผง Hi-Q',
    tags: ['นมผง', 'Hi-Q', 'ไฮคิว', 'สูตร3', 'แม่และเด็ก'],
    platform: 'shopee',
    storeName: 'Dumex Official Shop',
    storeType: 'mall',
    storeRating: 4.9,
    soldCount: 88000,
    basePrice: 1845,
    originalPrice: 2250,
    marketAvgPrice: 2050,
    estimatedFinalPrice: 1645,
    vipFinalPrice: 1545,
    hasOptionBait: false,
    thaiAuthenticityScore: 99,
    authenticitySummary: 'แม่ๆ คนไทยรีวิวตรวจสอบวันหมดอายุล็อตใหม่ ส่งด่วนแพ็คแน่นหนา',
    reviews: [
      {
        id: 'r11',
        author: 'คุณแม่ลูกสอง_ชลบุรี',
        comment: 'สั่งร้านทางการมั่นใจเรื่องของแท้และวันหมดอายุ ล็อตผลิตใหม่เอี่ยม หมดอายุปลายปีหน้า น้องทานสูตรนี้ขับถ่ายดีมากค่ะ สั่งประจำ',
        isAuthenticThai: true,
        authenticityNote: 'เช็ควันหมดอายุ และบริบทการเลี้ยงลูกของแม่ไทย',
        rating: 5,
        date: 'เมื่อวานนี้',
      }
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v11',
        code: 'MOMKID200',
        discountText: 'โค้ดแม่และเด็กลด 200.-',
        minSpend: 1800,
        discountAmount: 200,
        tag: 'แพลตฟอร์ม'
      }
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'shopee',
        price: 1845,
        estimatedAfterVoucher: 1645,
        storeName: 'Dumex Official (Shopee Mall)',
        storeType: 'mall',
        url: 'https://shopee.co.th/dumex_official',
        inStock: true,
      },
      {
        platform: 'lazada',
        price: 1899,
        estimatedAfterVoucher: 1719,
        storeName: 'Dumex Flagship (LazMall)',
        storeType: 'mall',
        url: 'https://www.lazada.co.th/shop/dumex',
        inStock: true,
      },
      {
        platform: 'tiktok',
        price: 1950,
        estimatedAfterVoucher: 1780,
        storeName: 'Hi-Q Thailand Shop',
        storeType: 'mall',
        url: 'https://www.tiktok.com/@hiqthailand',
        inStock: true,
      }
    ],
    stores: [
      {
        id: 's10-1',
        platform: 'shopee',
        storeName: 'Dumex Official (Shopee Mall)',
        storeType: 'mall',
        price: 1845,
        estimatedAfterVoucher: 1645,
        voucherNote: 'โค้ดแม่และเด็กลด 200.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 52000,
        isLowestOverall: true,
        url: 'https://shopee.co.th/dumex_official'
      },
      {
        id: 's10-2',
        platform: 'shopee',
        storeName: 'Baby & Mom Club (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 1870,
        estimatedAfterVoucher: 1690,
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 16000,
        url: 'https://shopee.co.th/babyandmom'
      },
      {
        id: 's10-3',
        platform: 'lazada',
        storeName: 'Dumex Flagship (LazMall)',
        storeType: 'mall',
        price: 1899,
        estimatedAfterVoucher: 1719,
        voucherNote: 'คูปอง LazMall ลด 150.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 12000,
        url: 'https://www.lazada.co.th/shop/dumex'
      },
      {
        id: 's10-4',
        platform: 'shopee',
        storeName: 'Kids Mall Official (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 1920,
        estimatedAfterVoucher: 1750,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 4200,
        url: 'https://shopee.co.th/kidsmall'
      },
      {
        id: 's10-5',
        platform: 'tiktok',
        storeName: 'Hi-Q Thailand Shop',
        storeType: 'mall',
        price: 1950,
        estimatedAfterVoucher: 1780,
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 3800,
        url: 'https://www.tiktok.com/@hiqthailand'
      }
    ],
    affiliateUrl: 'https://shope.ee/truedeal-hiq'
  },
  {
    id: 'deal-12',
    title: 'Hatari พัดลมปรับระดับ 18 นิ้ว รุ่น HT-S18M2 มอเตอร์พลังสูง ปรับความสูงได้ 6 ระดับ ปลอดภัยด้วยเทอร์โมฟิวส์',
    imageUrl: 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600&auto=format&fit=crop&q=80',
    category: 'พัดลม',
    tags: ['พัดลม', 'Hatari', 'ฮาตาริ', 'พัดลมสไลด์', '18นิ้ว', 'พัดลมตั้งพื้น', 'เครื่องใช้ไฟฟ้า'],
    platform: 'shopee',
    storeName: 'Hatari Official Store',
    storeType: 'mall',
    storeRating: 4.9,
    soldCount: 45000,
    basePrice: 890,
    originalPrice: 1290,
    marketAvgPrice: 990,
    estimatedFinalPrice: 810,
    vipFinalPrice: 760,
    activeViewersCount: 38,
    priceAdvice: 'buy_now',
    priceAdviceNote: 'ราคา ฿810 บน Shopee Mall ถูกสุดในรอบ 30 วัน แนะนำซื้อเลย',
    priceHistory: [
      { date: '30 วันก่อน', price: 990 },
      { date: '21 วันก่อน', price: 950 },
      { date: '14 วันก่อน', price: 890 },
      { date: '7 วันก่อน', price: 850 },
      { date: 'เมื่อวาน', price: 830 },
      { date: 'วันนี้', price: 810 },
    ],
    reviewHighlights: [
      { tag: 'ใบพัด 18 นิ้ว ลมแรงสะใจเย็นทั่วห้องโถง', type: 'pro', percentage: 99 },
      { tag: 'สไลด์ปรับความสูงง่าย ฐานแน่นหนาไม่สั่น', type: 'pro', percentage: 97 },
      { tag: 'มอเตอร์ทนทาน แบรนด์ฮาตาริไว้ใจได้', type: 'pro', percentage: 98 },
      { tag: 'กล่องขนาดค่อนข้างใหญ่ตอนจัดส่ง', type: 'con', percentage: 8 },
    ],
    voucherStackFormula: {
      basePrice: 890,
      platformDiscount: 80,
      storeDiscount: 40,
      shippingDiscount: 40,
      finalPrice: 810,
    },
    hasOptionBait: false,
    thaiAuthenticityScore: 98,
    authenticitySummary: 'พัดลมขวัญใจครอบครัวไทย ทนทาน ลมแรงสะใจ ใบพัด 18 นิ้ว เย็นทั่วห้อง',
    reviews: [
      {
        id: 'r12-1',
        author: 'สมชาย_คนรักบ้าน',
        comment: 'ใบพัด 18 นิ้วลมแรงมาก เปิดเบอร์ 1 ลมก็เย็นทั่วห้องโถงแล้ว ปรับระดับสูงต่ำง่าย ฐานแข็งแรงไม่โคลงเคลง',
        isAuthenticThai: true,
        authenticityNote: 'อธิบายการใช้งานจริงในบ้าน มีความเห็นชัดเจนเรื่องความแรงลม',
        rating: 5,
        date: '3 วันที่แล้ว',
      }
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v12-1',
        code: 'HATARI80',
        discountText: 'โค้ดส่วนลด Shopee Mall ลด 80.-',
        minSpend: 800,
        discountAmount: 80,
        tag: 'แพลตฟอร์ม'
      }
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'shopee',
        price: 890,
        estimatedAfterVoucher: 810,
        storeName: 'Hatari Official (Shopee Mall)',
        storeType: 'mall',
        url: 'https://shopee.co.th/hatari_official',
        inStock: true,
      },
      {
        platform: 'lazada',
        price: 915,
        estimatedAfterVoucher: 835,
        storeName: 'Hatari Flagship (LazMall)',
        storeType: 'mall',
        url: 'https://www.lazada.co.th/shop/hatari',
        inStock: true,
      },
      {
        platform: 'tiktok',
        price: 940,
        estimatedAfterVoucher: 880,
        storeName: 'Hatari Live Thailand (TikTok)',
        storeType: 'verified',
        url: 'https://www.tiktok.com/@hatarithailand',
        inStock: true,
      }
    ],
    stores: [
      {
        id: 's12-1',
        platform: 'shopee',
        storeName: 'Hatari Official Store (Shopee Mall)',
        storeType: 'mall',
        price: 890,
        estimatedAfterVoucher: 810,
        voucherNote: 'โค้ด Shopee Mall ลด 80.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 32000,
        isLowestOverall: true,
        url: 'https://shopee.co.th/hatari_official'
      },
      {
        id: 's12-2',
        platform: 'lazada',
        storeName: 'Hatari Flagship Store (LazMall)',
        storeType: 'mall',
        price: 915,
        estimatedAfterVoucher: 835,
        voucherNote: 'คูปอง LazMall ลด 80.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 18000,
        url: 'https://www.lazada.co.th/shop/hatari'
      },
      {
        id: 's12-3',
        platform: 'shopee',
        storeName: 'สหการไฟฟ้า บางกะปิ (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 930,
        estimatedAfterVoucher: 880,
        voucherNote: 'โค้ดร้านค้าลด 50.-',
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 6200,
        url: 'https://shopee.co.th/sahakarn_electric'
      },
      {
        id: 's12-4',
        platform: 'tiktok',
        storeName: 'Hatari Live Thailand (TikTok Shop)',
        storeType: 'verified',
        price: 940,
        estimatedAfterVoucher: 880,
        voucherNote: 'โค้ดส่งฟรี + คูปอง 60.-',
        freeShipping: true,
        storeRating: 4.7,
        soldCount: 3900,
        url: 'https://www.tiktok.com/@hatarithailand'
      },
      {
        id: 's12-5',
        platform: 'shopee',
        storeName: 'เครื่องใช้ไฟฟ้าประชาราษฎร์ (Shopee ทั่วไป)',
        storeType: 'regular',
        price: 960,
        estimatedAfterVoucher: 940,
        freeShipping: false,
        storeRating: 4.6,
        soldCount: 1100,
        url: 'https://shopee.co.th/pracharat_electric'
      }
    ],
    affiliateUrl: 'https://shope.ee/truedeal-hatari18'
  },
  {
    id: 'deal-13',
    title: 'Xiaomi Smart Standing Fan 2 Lite พัดลมตั้งพื้นอัจฉริยะ ลมธรรมชาติเงียบสงบ สั่งการผ่านเสียงและแอป Mi Home',
    imageUrl: 'https://images.unsplash.com/photo-1563298723-dcfebaa392e3?w=600&auto=format&fit=crop&q=80',
    category: 'พัดลม',
    tags: ['พัดลม', 'Xiaomi', 'เสียวหมี่', 'พัดลมตั้งพื้น', 'Smart Fan', 'พัดลมอัจฉริยะ', 'พัดลมเงียบ'],
    platform: 'shopee',
    storeName: 'Xiaomi Official Store',
    storeType: 'mall',
    storeRating: 4.9,
    soldCount: 28000,
    basePrice: 1190,
    originalPrice: 1690,
    marketAvgPrice: 1390,
    estimatedFinalPrice: 1090,
    vipFinalPrice: 1020,
    activeViewersCount: 24,
    priceAdvice: 'buy_now',
    priceAdviceNote: 'ราคา ฿1,090 บน Shopee Mall ถูกที่สุดในรอบ 30 วัน ซื้อได้เลย',
    priceHistory: [
      { date: '30 วันก่อน', price: 1490 },
      { date: '21 วันก่อน', price: 1350 },
      { date: '14 วันก่อน', price: 1250 },
      { date: '7 วันก่อน', price: 1190 },
      { date: 'เมื่อวาน', price: 1150 },
      { date: 'วันนี้', price: 1090 },
    ],
    reviewHighlights: [
      { tag: 'เสียงเงียบสนิท เหมาะกับห้องนอนมาก', type: 'pro', percentage: 99 },
      { tag: 'สั่งงานผ่านแอป Mi Home และ Google ได้ทันที', type: 'pro', percentage: 97 },
      { tag: 'ลมธรรมชาติ 7 ใบพัด พัดสบายไม่เวียนหัว', type: 'pro', percentage: 95 },
      { tag: 'ต้องประกอบเองเล็กน้อย ใช้เวลาประมาณ 5 นาที', type: 'con', percentage: 10 },
    ],
    voucherStackFormula: {
      basePrice: 1190,
      platformDiscount: 100,
      storeDiscount: 50,
      shippingDiscount: 45,
      finalPrice: 1090,
    },
    hasOptionBait: false,
    thaiAuthenticityScore: 97,
    authenticitySummary: 'พัดลมสายมินิมอลยอดนิยม รีวิวต่อ Wi-Fi และสั่งงานผ่านแอปง่าย เสียงเงียบมากเหมาะกับห้องนอน',
    reviews: [
      {
        id: 'r13-1',
        author: 'Nut_SmartHome',
        comment: 'ชอบมากครับ ต่อกับ Mi Home ได้ไว สั่ง Google Assistant เปิดปิดผ่านเสียงได้ ลมเงียบมาก เหมาะกับห้องนอนเด็ก',
        isAuthenticThai: true,
        authenticityNote: 'ภาษาพูดคนไทย ทดสอบระบบ Smart Home จริง',
        rating: 5,
        date: '1 วันที่แล้ว',
      }
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v13-1',
        code: 'XIAOMI100',
        discountText: 'โค้ดส่วนลด Xiaomi ลด 100.-',
        minSpend: 1000,
        discountAmount: 100,
        tag: 'แพลตฟอร์ม'
      }
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'shopee',
        price: 1190,
        estimatedAfterVoucher: 1090,
        storeName: 'Xiaomi Official (Shopee Mall)',
        storeType: 'mall',
        url: 'https://shopee.co.th/xiaomi_official',
        inStock: true,
      },
      {
        platform: 'lazada',
        price: 1220,
        estimatedAfterVoucher: 1120,
        storeName: 'Xiaomi Flagship (LazMall)',
        storeType: 'mall',
        url: 'https://www.lazada.co.th/shop/xiaomi',
        inStock: true,
      },
      {
        platform: 'tiktok',
        price: 1290,
        estimatedAfterVoucher: 1190,
        storeName: 'Xiaomi Thailand Shop (TikTok)',
        storeType: 'mall',
        url: 'https://www.tiktok.com/@xiaomi_th',
        inStock: true,
      }
    ],
    stores: [
      {
        id: 's13-1',
        platform: 'shopee',
        storeName: 'Xiaomi Official Store (Shopee Mall)',
        storeType: 'mall',
        price: 1190,
        estimatedAfterVoucher: 1090,
        voucherNote: 'โค้ดส่วนลด Mall ลด 100.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 19500,
        isLowestOverall: true,
        url: 'https://shopee.co.th/xiaomi_official'
      },
      {
        id: 's13-2',
        platform: 'lazada',
        storeName: 'Xiaomi Flagship Store (LazMall)',
        storeType: 'mall',
        price: 1220,
        estimatedAfterVoucher: 1120,
        voucherNote: 'คูปอง LazMall ลด 100.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 11200,
        url: 'https://www.lazada.co.th/shop/xiaomi'
      },
      {
        id: 's13-3',
        platform: 'shopee',
        storeName: 'Mi Thailand Gadget Store (Shopee ร้านแนะนำ)',
        storeType: 'preferred',
        price: 1250,
        estimatedAfterVoucher: 1170,
        voucherNote: 'โค้ดร้านลด 80.-',
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 4300,
        url: 'https://shopee.co.th/mi_gadget_th'
      },
      {
        id: 's13-4',
        platform: 'tiktok',
        storeName: 'Xiaomi Thailand Shop (TikTok Shop)',
        storeType: 'mall',
        price: 1290,
        estimatedAfterVoucher: 1190,
        voucherNote: 'โค้ดไลฟ์สดลด 100.-',
        freeShipping: true,
        storeRating: 4.8,
        soldCount: 2800,
        url: 'https://www.tiktok.com/@xiaomi_th'
      },
      {
        id: 's13-5',
        platform: 'shopee',
        storeName: 'อุปกรณ์ไอทีคลองถม (Shopee ทั่วไป)',
        storeType: 'regular',
        price: 1320,
        estimatedAfterVoucher: 1290,
        freeShipping: false,
        storeRating: 4.6,
        soldCount: 650,
        url: 'https://shopee.co.th/it_klongthom'
      }
    ],
    affiliateUrl: 'https://shope.ee/truedeal-xiaomifan'
  },
  {
    id: 'deal-14',
    title: 'Dreame L10s Ultra หุ่นยนต์ดูดฝุ่นถูพื้นอัจฉริยะ ซักม็อบเป่าแห้งอัตโนมัติ แท่นชาร์จ All-in-One ประกันศูนย์ไทย 2 ปี',
    imageUrl: 'https://images.unsplash.com/photo-1518640467707-6811f4a6ab73?w=600&auto=format&fit=crop&q=80',
    category: 'เครื่องใช้ไฟฟ้า',
    tags: ['หุ่นยนต์ดูดฝุ่น', 'Dreame', 'ดูดฝุ่น', 'เครื่องใช้ไฟฟ้า', 'ของใช้ในบ้าน'],
    platform: 'lazada',
    storeName: 'Dreame Official Flagship Store (LazMall)',
    storeType: 'mall',
    storeRating: 4.9,
    soldCount: 3200,
    basePrice: 19990,
    originalPrice: 28990,
    marketAvgPrice: 22500,
    estimatedFinalPrice: 18490,
    vipFinalPrice: 17990,
    activeViewersCount: 34,
    priceAdvice: 'buy_now',
    priceAdviceNote: 'ราคา ฿18,490 บน Lazada จัดโปรโมชันแถมน้ำยาทำความสะอาดและผ้าม็อบ 2 ชุด คุ้มค่าที่สุด',
    priceHistory: [
      { date: '30 วันก่อน', price: 23990 },
      { date: '15 วันก่อน', price: 21990 },
      { date: '7 วันก่อน', price: 19990 },
      { date: 'วันนี้', price: 18490 },
    ],
    reviewHighlights: [
      { tag: 'ซักม็อบสะอาด เป่าแห้งลมร้อนไม่มีกลิ่นอับ', type: 'pro', percentage: 98 },
      { tag: 'แผนที่เลเซอร์แม่นยำ ไม่ชนเฟอร์นิเจอร์', type: 'pro', percentage: 95 },
      { tag: 'แรงดูด 5,300Pa เก็บขนแมวเกลี้ยง', type: 'pro', percentage: 96 },
      { tag: 'แท่นชาร์จมีขนาดใหญ่ ต้องเผื่อพื้นที่วาง', type: 'con', percentage: 15 },
    ],
    voucherStackFormula: {
      basePrice: 19990,
      platformDiscount: 1000,
      storeDiscount: 500,
      shippingDiscount: 0,
      finalPrice: 18490,
    },
    hasOptionBait: false,
    thaiAuthenticityScore: 99,
    authenticitySummary: 'ร้านค้าทางการ Dreame LazMall แท้ 100% รับประกันศูนย์ไทย 2 ปีเต็ม',
    reviews: [
      {
        id: 'r14-1',
        author: 'คุณพัชรินทร์ ว.',
        comment: 'ดีมากกกก ชีวิตสบายขึ้น 300% กวาดถูสะอาดเกลี้ยง ม็อบซักเองเป่าแห้งเอง ไม่มีกลิ่นอับเลย คุ้มค่าเงินที่สุดค่ะ',
        isAuthenticThai: true,
        authenticityNote: 'ผู้ซื้อจริง มีภาพรีวิวห้องคอนโดในไทย',
        rating: 5,
        date: '2 วันที่แล้ว',
      },
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v14-1',
        code: 'DREAME1000',
        discountText: 'ลดทันที ฿1,000 เมื่อช้อปครบ ฿15,000',
        minSpend: 15000,
        discountAmount: 1000,
        tag: 'ร้านค้า',
      },
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'lazada',
        storeName: 'Dreame LazMall',
        price: 19990,
        estimatedAfterVoucher: 18490,
        storeType: 'mall',
        inStock: true,
        url: 'https://c.lazada.co.th/t/c.truedeal-dreame',
      },
      {
        platform: 'shopee',
        storeName: 'Dreame Shopee Mall',
        price: 20490,
        estimatedAfterVoucher: 18990,
        storeType: 'mall',
        inStock: true,
        url: 'https://shope.ee/truedeal-dreame',
      },
    ],
    stores: [
      {
        id: 's14-1',
        platform: 'lazada',
        storeName: 'Dreame Official Flagship Store (LazMall)',
        storeType: 'mall',
        price: 19990,
        estimatedAfterVoucher: 18490,
        voucherNote: 'โค้ดลด LazMall 1,500.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 3200,
        url: 'https://c.lazada.co.th/t/c.truedeal-dreame',
      },
    ],
    affiliateUrl: 'https://c.lazada.co.th/t/c.truedeal-dreame',
  },
  {
    id: 'deal-15',
    title: 'Sony WH-1000XM5 หูฟังไร้สายครอบหู พรีเมียมตัดเสียงรบกวนชั้นนำ ไมค์ชัด 8 ตัว ประกันศูนย์โซนี่ไทย 1 ปี',
    imageUrl: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=600&auto=format&fit=crop&q=80',
    category: 'หูฟังบลูทูธ',
    tags: ['หูฟัง', 'Sony', 'บลูทูธ', 'ANC', 'ไอที & แกดเจ็ต'],
    platform: 'shopee',
    storeName: 'Sony Official Store (Shopee Mall)',
    storeType: 'mall',
    storeRating: 4.9,
    soldCount: 5400,
    basePrice: 11990,
    originalPrice: 14990,
    marketAvgPrice: 13200,
    estimatedFinalPrice: 10490,
    vipFinalPrice: 9990,
    activeViewersCount: 42,
    priceAdvice: 'buy_now',
    priceAdviceNote: 'ราคา ฿10,490 บน Shopee Mall ถูกกว่าราคาเฉลี่ยหน้าร้าน ฿2,710 คุ้มค่าที่สุดสำหรับหูฟังตัดเสียงระดับท็อป',
    priceHistory: [
      { date: '30 วันก่อน', price: 13990 },
      { date: '15 วันก่อน', price: 12500 },
      { date: '7 วันก่อน', price: 11990 },
      { date: 'วันนี้', price: 10490 },
    ],
    reviewHighlights: [
      { tag: 'ตัดเสียงเครื่องบิน เสียงคาเฟ่ เงียบสนิท', type: 'pro', percentage: 99 },
      { tag: 'ไมค์ 8 ตัว ประชุมสายเสียงชัดเจนมาก', type: 'pro', percentage: 97 },
      { tag: 'น้ำหนักเบา ใส่สบายไม่เจ็บกระหม่อม', type: 'pro', percentage: 94 },
      { tag: 'พับก้านไม่ได้เหมือนรุ่น XM4', type: 'con', percentage: 18 },
    ],
    voucherStackFormula: {
      basePrice: 11990,
      platformDiscount: 1000,
      storeDiscount: 500,
      shippingDiscount: 0,
      finalPrice: 10490,
    },
    hasOptionBait: false,
    thaiAuthenticityScore: 99,
    authenticitySummary: 'Sony Official Store ของแท้ 100% ประกันศูนย์ Sony Thailand 1 ปีเต็ม',
    reviews: [
      {
        id: 'r15-1',
        author: 'K. Tanakorn',
        comment: 'ระบบตัดเสียงดีสมคำร่ำลือ ใส่ทำงานในออฟฟิศคือโลกเงียบสงบ ไมค์คุยโทรศัพท์ชัดเจนมาก คุ้มราคาครับ',
        isAuthenticThai: true,
        authenticityNote: 'ผู้ซื้อจริง verified purchase',
        rating: 5,
        date: '2 วันที่แล้ว',
      },
    ],
    freeShipping: true,
    availableVouchers: [
      {
        id: 'v15-1',
        code: 'SONY1000',
        discountText: 'โค้ดส่วนลด ฿1,000 ขั้นต่ำ ฿10,000',
        minSpend: 10000,
        discountAmount: 1000,
        tag: 'ร้านค้า',
      },
    ],
    isAbsoluteCheapest: true,
    priceComparisons: [
      {
        platform: 'shopee',
        storeName: 'Sony Shopee Mall',
        price: 11990,
        estimatedAfterVoucher: 10490,
        storeType: 'mall',
        inStock: true,
        url: 'https://shope.ee/truedeal-sonyxm5',
      },
      {
        platform: 'lazada',
        storeName: 'Sony LazMall',
        price: 12490,
        estimatedAfterVoucher: 10990,
        storeType: 'mall',
        inStock: true,
        url: 'https://c.lazada.co.th/t/c.truedeal-sonyxm5',
      },
    ],
    stores: [
      {
        id: 's15-1',
        platform: 'shopee',
        storeName: 'Sony Official Store (Shopee Mall)',
        storeType: 'mall',
        price: 11990,
        estimatedAfterVoucher: 10490,
        voucherNote: 'โค้ดลด Shopee Mall 1,500.-',
        freeShipping: true,
        storeRating: 4.9,
        soldCount: 5400,
        url: 'https://shope.ee/truedeal-sonyxm5',
      },
    ],
    affiliateUrl: 'https://shope.ee/truedeal-sonyxm5',
  }
];

